'use strict';

const express = require('express');
let bcrypt;
try {
  bcrypt = require('bcryptjs');
} catch (_) {
  bcrypt = require('bcrypt');
}
const pool = require('../../database/db');
const { authenticate, requireRole } = require('../../middleware/auth');
const { sha256, createESignManifest } = require('../../services/eSignManifestService');
const { makeTextPdf } = require('../../services/pdfExportService');
const { CASE_SCOPED_AUDIT_ENTITIES, buildChronologyLines } = require('../../services/inspectorExportService');

const router = express.Router();

router.post('/audit/inspector-export', authenticate, requireRole('admin', 'platform_admin'), async (req, res) => {
  try {
    const caseId = Number(req.body.case_id);
    if (!caseId) return res.status(400).json({ error: 'case_id is required.' });
    const password = String(req.body.e_sign_password || req.body.password || '');
    const reason = String(req.body.e_sign_reason || req.body.reason || '').trim();
    if (String(req.body.format || '').toLowerCase() === 'pdf' && (!password || !reason)) {
      return res.status(400).json({ error: 'e_sign_password and e_sign_reason are required for signed PDF export.' });
    }
    if (password) {
      const [[userWithHash]] = await pool.execute('SELECT password FROM users WHERE id=? LIMIT 1', [req.user.userId]);
      const valid = userWithHash?.password ? await bcrypt.compare(password, userWithHash.password) : false;
      if (!valid) return res.status(401).json({ error: 'Incorrect password. Electronic signature rejected.' });
    }
    // PAUD-4 item 3: this ordered by `changed_at`, which does not exist on
    // case_audit_trail (the column is `timestamp`). The query threw, the catch
    // below swallowed it, and every inspector pack was silently produced with an
    // EMPTY chronology — signed, and containing nothing. Found 2026-08-05 while
    // browser-verifying the truncation fix.
    //
    // The catch is kept for deployments where the table is absent, but it now
    // says so instead of failing silently. An audit artifact that quietly
    // contains nothing is worse than one that errors.
    const [audit] = await pool.execute(
      'SELECT * FROM case_audit_trail WHERE case_id=? ORDER BY timestamp ASC',
      [caseId]
    ).catch(async (err) => {
      console.error(`inspector-export: case_audit_trail query failed for case ${caseId} — chronology will be empty:`, err.message);
      return [ [] ];
    });
    const entityPlaceholders = CASE_SCOPED_AUDIT_ENTITIES.map(() => '?').join(',');
    const [generic] = await pool.execute(
      `SELECT * FROM audit_logs WHERE entity_id=? AND entity IN (${entityPlaceholders}) ORDER BY created_at ASC`,
      [caseId, ...CASE_SCOPED_AUDIT_ENTITIES]
    ).catch(async (err) => {
      console.error(`inspector-export: audit_logs query failed for case ${caseId}:`, err.message);
      return [ [] ];
    });
    const payload = { case_id: caseId, generated_at: new Date().toISOString(), audit, generic, signature_manifest: { hash: sha256(JSON.stringify({ audit, generic })) } };
    if (process.env.ESIGN_PRIVATE_KEY_PATH) {
      payload.signature_manifest = await createESignManifest({
        signer_user_id: req.user.userId,
        signer_email: req.user.email,
        intent_string: `Inspector audit export for case ${caseId}: ${reason || 'Inspector export'}`,
        signed_object: payload,
      });
    }
    if (String(req.body.format || '').toLowerCase() === 'pdf') {
      const lines = [
        `Case ID: ${caseId}`,
        `Generated: ${payload.generated_at}`,
        `Generated by: ${req.user.email}`,
        `Audit rows: ${audit.length}`,
        `Generic audit rows: ${generic.length}`,
        `Content hash: ${payload.signature_manifest.content_hash || payload.signature_manifest.hash}`,
        `Manifest ID: ${payload.signature_manifest.manifest_id || 'not configured'}`,
        '',
        'Chronology',
        ...buildChronologyLines(audit),
      ];
      const pdf = makeTextPdf('MIMS Inspector Audit Export', lines);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="mims-case-${caseId}-audit-export.pdf"`);
      return res.send(pdf);
    }
    res.json({ format: 'json-pdf-ready', payload, note: 'PDF rendering can consume this signed payload in the deployment environment.' });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

module.exports = router;
