'use strict';

const express = require('express');
let bcrypt;
try {
  bcrypt = require('bcryptjs');
} catch (_) {
  bcrypt = require('bcrypt');
}
const pool = require('../../database/db');
const { authenticate, requireRole } = require('../../middleware/auth');
const { sha256, createESignManifest } = require('../../services/eSignManifestService');
const { makeTextPdf } = require('../../services/pdfExportService');

const router = express.Router();

router.post('/audit/inspector-export', authenticate, requireRole('admin', 'platform_admin'), async (req, res) => {
  try {
    const caseId = Number(req.body.case_id);
    if (!caseId) return res.status(400).json({ error: 'case_id is required.' });
    const password = String(req.body.e_sign_password || req.body.password || '');
    const reason = String(req.body.e_sign_reason || req.body.reason || '').trim();
    if (String(req.body.format || '').toLowerCase() === 'pdf' && (!password || !reason)) {
      return res.status(400).json({ error: 'e_sign_password and e_sign_reason are required for signed PDF export.' });
    }
    if (password) {
      const [[userWithHash]] = await pool.execute('SELECT password FROM users WHERE id=? LIMIT 1', [req.user.userId]);
      const valid = userWithHash?.password ? await bcrypt.compare(password, userWithHash.password) : false;
      if (!valid) return res.status(401).json({ error: 'Incorrect password. Electronic signature rejected.' });
    }
    const [audit] = await pool.execute('SELECT * FROM case_audit_trail WHERE case_id=? ORDER BY changed_at ASC', [caseId]).catch(async () => [ [] ]);
    const [generic] = await pool.execute('SELECT * FROM audit_logs WHERE entity_id=? ORDER BY created_at ASC', [caseId]).catch(async () => [ [] ]);
    const payload = { case_id: caseId, generated_at: new Date().toISOString(), audit, generic, signature_manifest: { hash: sha256(JSON.stringify({ audit, generic })) } };
    if (process.env.ESIGN_PRIVATE_KEY_PATH) {
      payload.signature_manifest = await createESignManifest({
        signer_user_id: req.user.userId,
        signer_email: req.user.email,
        intent_string: `Inspector audit export for case ${caseId}: ${reason || 'Inspector export'}`,
        signed_object: payload,
      });
    }
    if (String(req.body.format || '').toLowerCase() === 'pdf') {
      const lines = [
        `Case ID: ${caseId}`,
        `Generated: ${payload.generated_at}`,
        `Generated by: ${req.user.email}`,
        `Audit rows: ${audit.length}`,
        `Generic audit rows: ${generic.length}`,
        `Content hash: ${payload.signature_manifest.content_hash || payload.signature_manifest.hash}`,
        `Manifest ID: ${payload.signature_manifest.manifest_id || 'not configured'}`,
        '',
        'Chronology',
        ...audit.slice(0, 34).map((row) => `${row.changed_at || row.created_at || ''} ${row.action || row.change_type || ''} ${row.field_name || row.field || ''}`),
      ];
      const pdf = makeTextPdf('MIMS Inspector Audit Export', lines);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="mims-case-${caseId}-audit-export.pdf"`);
      return res.send(pdf);
    }
    res.json({ format: 'json-pdf-ready', payload, note: 'PDF rendering can consume this signed payload in the deployment environment.' });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

module.exports = router;
