import { useEffect, useState } from 'react'
import { httpFetch } from '../api/httpFetch.js'

const roles = ['suspect','co_suspect','concomitant','interacting']
const blank = { role: 'suspect', drug_name_verbatim: '', whodrug_code: '', dose_amount: '', dose_unit: '', route_of_administration: '', indication: '', start_date: '', end_date: '', action_taken: 'unknown', drug_reaction_recurrence: 'unknown', lot_number: '' }
export default function CaseDrugsTab({ caseId, headers }) {
  const [rows, setRows] = useState([]); const [form, setForm] = useState(blank)
  async function load() { const res = await httpFetch(`/api/cases/${caseId}/drugs`, { headers }); const data = await res.json(); setRows(data.rows || []) }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { if (caseId) load() }, [caseId])
  async function add(e) { e.preventDefault(); const res = await httpFetch(`/api/cases/${caseId}/drugs`, { method: 'POST', headers, body: JSON.stringify(form) }); const data = await res.json(); if (res.ok) { setRows(data.rows || []); setForm(blank) } }
  async function del(id) { const res = await httpFetch(`/api/cases/${caseId}/drugs/${id}`, { method: 'DELETE', headers }); if (res.ok) setRows(rows.filter(r => r.id !== id)) }
  const set = (k, v) => setForm(p => ({ ...p, [k]: v }))
  return <div className="cf-drugs-tab"><h3>Drug Roles</h3><table className="cf-multirow-table"><thead><tr>{['Role','Drug Name','WHODrug','Dose','Route','Indication','Start','End','Action','Recurrence','Lot',''].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r => <tr key={r.id}><td><span className={`cf-role-badge ${r.role}`}>{r.role}</span></td><td>{r.drug_name_verbatim}</td><td>{r.whodrug_code}</td><td>{[r.dose_amount, r.dose_unit].filter(Boolean).join(' ')}</td><td>{r.route_of_administration}</td><td>{r.indication}</td><td>{r.start_date}</td><td>{r.end_date}</td><td>{r.action_taken}</td><td>{r.drug_reaction_recurrence}</td><td>{r.lot_number}</td><td><button onClick={() => del(r.id)}>Remove</button></td></tr>)}</tbody></table><form className="cf-drug-form" onSubmit={add}><select value={form.role} onChange={e => set('role', e.target.value)}>{roles.map(r => <option key={r} value={r}>{r}</option>)}</select><input placeholder="Drug name" value={form.drug_name_verbatim} onChange={e => set('drug_name_verbatim', e.target.value)} /><input placeholder="WHO code" value={form.whodrug_code} onChange={e => set('whodrug_code', e.target.value)} /><input placeholder="Dose" value={form.dose_amount} onChange={e => set('dose_amount', e.target.value)} /><input placeholder="Unit" value={form.dose_unit} onChange={e => set('dose_unit', e.target.value)} /><input placeholder="Route" value={form.route_of_administration} onChange={e => set('route_of_administration', e.target.value)} /><input placeholder="Indication" value={form.indication} onChange={e => set('indication', e.target.value)} /><input type="date" value={form.start_date} onChange={e => set('start_date', e.target.value)} /><input type="date" value={form.end_date} onChange={e => set('end_date', e.target.value)} /><input placeholder="Lot" value={form.lot_number} onChange={e => set('lot_number', e.target.value)} /><button>+ Add Drug</button></form></div>
}
